export default [
	{
		name: 'this website',
		color: '#4789F0',
		client: 'myself',
		slug: 'my-website',
		brief:
			'Rebuilding my website pretty much every year, this one is aimed to last a couple. Built from the  ground-up using Next.js, it has all the things that  are meant to impress whomever’s conidering to hire me - sleek design, sexy animations, offline first, React, SSR, all the works.',
		scopes: ['ui', 'ux', 'dev'],
	},
	{
		name: 'storehub website',
		color: '#DB923A',
		client: 'storehub',
		slug: 'storehub-website',
		brief: 'Storehub Website.',
		scopes: ['ui', 'dev'],
	},
	{
		name: 'storehub display',
		color: '#C46128',
		client: 'storehub',
		slug: 'storehub-display',
		brief: 'Storehub Display.',
		scopes: ['dev'],
	},
	{
		name: 'veld website',
		color: '#4B6CFF',
		client: 'veld',
		slug: 'veld-website',
		brief: 'Veld website.',
		scopes: ['ui', 'ux', 'dev', 'devops'],
	},
	{
		name: 'convertable',
		color: '#157FE8',
		client: 'myself',
		slug: 'convertable',
		brief: 'Currency calculator and converter.',
		scopes: ['ui', 'dev'],
	},
	{
		name: 'sandstone.js',
		color: '#C75A50',
		client: 'myself',
		slug: 'sandstone',
		brief: 'Web Components library',
		scopes: ['dev'],
	},
	{
		name: 'kdm',
		color: '#20252D',
		client: 'myself',
		slug: 'kdm',
		brief: 'Killer Deployment Machine.',
		scopes: ['dev', 'devops'],
	},
	{
		name: 'vave',
		color: '#665DE2',
		client: 'myself',
		slug: 'vave',
		brief: 'Ultimate stack goodizer.',
		scopes: ['ux', 'dx', 'dev'],
	},
];
