export default [
	{
		name: 'this website',
		color: '#4789F0',
		client: 'myself',
		slug: 'my-website',
		brief:
			'Rebuilding my website pretty much every year, this one is aimed to last a couple. Built from the  ground-up using Next.js, it has all the things that  are meant to impress whomever’s conidering to hire me - sleek design, sexy animations, offline first, React, SSR, all the works.',
		scopes: ['ui', 'ux', 'dev'],
		image: '/static/work/previews/website.svg',
	},
	{
		name: 'storehub website',
		color: '#DB923A',
		client: 'storehub',
		slug: 'storehub-website',
		brief:
			"StoreHub is a Malaysian point of sales company. Company's primary focus is to transform retail experience and make it better for everyone, and company website needed to refect that and be wow-y for the users.",
		scopes: ['ui', 'dev'],
		image: '/static/work/previews/storehub-website.jpg',
	},
	{
		name: 'storehub display',
		color: '#C46128',
		client: 'storehub',
		slug: 'storehub-display',
		brief: 'Storehub Display.',
		scopes: ['dev'],
		image: '/static/work/previews/storehub-cfd.jpg',
	},
	// {
	// 	name: 'veld website',
	// 	color: '#4B6CFF',
	// 	client: 'veld',
	// 	slug: 'veld-website',
	// 	brief: 'Veld website.',
	// 	scopes: ['ui', 'ux', 'dev', 'devops'],
	// 	image: '/static/work/previews/veld.jpg',
	// },
	{
		name: 'convertable',
		color: '#157FE8',
		client: 'myself',
		slug: 'convertable',
		brief: 'Currency calculator and converter.',
		scopes: ['ui', 'dev'],
		image: '/static/work/previews/convertable.jpg',
	},
	{
		name: 'sandstone.js',
		color: '#C75A50',
		client: 'the world',
		slug: 'sandstone',
		brief: 'Web Components library',
		scopes: ['dev'],
		image: '/static/work/previews/sandstone.jpg',
	},
	// {
	// 	name: 'kdm',
	// 	color: '#20252D',
	// 	client: 'myself',
	// 	slug: 'kdm',
	// 	brief: 'Killer Deployment Machine.',
	// 	scopes: ['dev', 'devops'],
	// },
	{
		name: 'vave',
		color: '#665DE2',
		client: 'myself',
		slug: 'vave',
		brief: 'Ultimate stack goodizer.',
		scopes: ['ux', 'dx', 'dev'],
		image: '/static/work/previews/vave.jpg',
	},
	{
		name: 'myplate',
		color: '#665DE2',
		client: 'a hackathon',
		slug: 'myplate',
		brief: 'Smart parking and toll payments.',
		scopes: ['dev'],
		image: '/static/work/previews/vave.jpg',
	},
	{
		name: 'mindway',
		color: '#665DE2',
		client: 'a hackathon',
		slug: 'mindway',
		brief: 'Preventive mood tracker.',
		scopes: ['dev'],
		image: '/static/work/previews/vave.jpg',
	},
];
